export const PATHS = {
  LOGIN: "/login",
  LOGIN_OTP: "/login-2fa",
  SIGNUP: "/auth/registration",
  FORGOT_PASSWORD: "/auth/forgot-password",
  SET_PASSWORD: "/auth/confirm-new-password",
  VERIFY_OTP: "/auth/verify-otp",
  ACCOUNT_SUCCESSFUL: "/auth/account-created",
  LIVESCORE: "/livescore",
  REGISTRATION_TYPE: "/auth/registration-type",
  NOTIFICATION:"/notifications",
  FEED: "/feed",
  HOME: "/",
  NETWORK: "/network",
  OTHER_USER_PROFILE: "/via",
  SETTINGS: {
    PROFILE: "/settings/profile",
    PASSWORD_RESET: "/settings/reset-password",
     MY_REFERRALS: "/settings/my-referrals",
    NOTIFICATIONS: "/settings/notifications",
    ACTIVITIES: "/settings/activities",
    FAQ: "/settings/faqs",
  },
  MESSAGES: "/messages",
  MARKETPLACE: "/market-place",
  NOTIFICATIONS: "/notifications",
  PROFILE: "/profile",
  GET_STARTED: "/get-started",
  EDIT_PROFILE: "/edit-profile",
  PRIVACY_POLICY: "/privacy-policy",
  TERMS_OF_USE: "/term-of-use",
  COOKIE_POLICY: "/cookie-policy",
  CHALLENGE: { LEADERBOARD: "/challenge/leaderboard" },
ACTIVITY_STAT:{
MY_PROFILE_VIEWS :"/activities/profile-views"
}
};
